trigger:
- main

pr:
  branches:
    include:
    - '*'

stages:
- stage: Plan
  jobs:
  - job: terraformPlan
    pool:
      name: 'my-pool'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - script: |
        cd infrastructure-terraform
        terraform init
        terraform plan
      displayName: 'Terraform Plan'
    condition: eq(variables['Build.Reason'], 'PullRequest')

- stage: Apply
  dependsOn: Plan
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: terraformApply
    pool:
      name: 'my-pool'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - script: |
        cd infrastructure-terraform
        terraform init
        terraform apply -auto-approve
      displayName: 'Terraform Apply'
